name: CI solamente

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Descarga el repositorio en el ejecutor

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "adopt"
          server-id: github
          settings-path: ${{ github.workspace }} # UbicaciÃ³n del archivo settings.xml

      - name: Build
        uses: gradle/gradle-build-action@v2.6.0
        with:
          gradle-version: 2.1

      - name: Build del Front
        working-directory: src/Clients
        run: ./gradlew build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Clients
          path: src/Clients/build/libs

      - name: Build del Back
        working-directory: src/Backend/OrderService
        run: ./gradlew build test

      - name: Dockerizar el front y el backend
        run: |
          cp src/Clients/build/libs/*.war deploy/docker/Clients/drop # Copiar el resultado del build para la nueva imagen
          docker build -t p2gps/web deploy/docker/Clients
          cp src/Backend/OrderService/build/libs/ordering* deploy/docker/Order/drop # Copiar el resultado del build para la nueva imagen
          docker build -t p2gps/order deploy/docker/Order

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Crear los secretos en Settings -> Secrets/Actions/New Repository Secret
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Etiquetar con formato DockerHub
        run: |
          docker tag p2gps/web ${{ secrets.DOCKERHUB_USERNAME }}/p2gps:web
          docker tag p2gps/order ${{ secrets.DOCKERHUB_USERNAME }}/p2gps:order

      - name: Push a DockerHub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/p2gps:order
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/p2gps:web
